FROM golang:1.14 AS builder
WORKDIR /app
COPY go.mod /app
COPY go.sum /app
RUN go mod download
COPY . /app

RUN CGO_ENABLED=0 go build -o main cmd/api/main.go

FROM alpine:3.11

RUN apk --no-cache add ca-certificates

WORKDIR /root

COPY --from=builder /app/main .
COPY --from=builder /app/cmd/api/config.yaml /root/cmd/api/

EXPOSE 8080
CMD ["./main"]